# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 15:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 18, 15, 11, 58, 371651, tzinfo=utc)),
        ),
    ]
