# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20160523_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liek',
            new_name='likes',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 8, 3, 15, 1794, tzinfo=utc)),
        ),
    ]
