# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 11:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_postsocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 11, 28, 58, 693549, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postsocial',
            name='commented_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 11, 28, 58, 694534, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='postsocial',
            name='liked_at',
        ),
        migrations.RemoveField(
            model_name='postsocial',
            name='likes',
        ),
        migrations.AlterUniqueTogether(
            name='postsocial',
            unique_together=set([('user', 'post')]),
        ),
    ]
