# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 12:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_auto_20160523_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post Detail'},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'verbose_name': 'Post Comment'},
        ),
        migrations.AlterModelOptions(
            name='postlikes',
            options={'verbose_name': 'Post Like'},
        ),
        migrations.AddField(
            model_name='postlikes',
            name='post_id_meta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postlikes',
            name='user_email',
            field=models.EmailField(default='saru.sreyo@gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 12, 19, 51, 500575, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='comment_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 12, 19, 51, 502178, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postlikes',
            name='liked_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 12, 19, 51, 501463, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='postlikes',
            unique_together=set([('user_email', 'post_id_meta')]),
        ),
    ]
