# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 12:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_auto_20160523_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 12, 20, 35, 326607, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='comment_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 12, 20, 35, 328421, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postlikes',
            name='liked_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 12, 20, 35, 327619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postlikes',
            name='user_email',
            field=models.EmailField(default='default@gmail.com', max_length=255),
        ),
    ]
