# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0002_requestlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlist',
            name='friend_email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
