# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0011_auto_20160519_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='requestlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='RequestList',
        ),
    ]
