# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 05:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Friends', '0012_auto_20160519_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=255)),
                ('friend_email', models.EmailField(max_length=255)),
                ('friend_type', models.CharField(max_length=50)),
                ('request_type', models.CharField(max_length=20)),
                ('friend_since', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set([('user_email', 'friend_email')]),
        ),
    ]
