# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0013_auto_20160520_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friend_since',
            field=models.DateTimeField(null=True),
        ),
    ]
