# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0015_requestlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='RequestList',
        ),
    ]
