# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0017_auto_20160520_0801'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set([('user_email', 'friend_email'), ('friend_email', 'user_email')]),
        ),
        migrations.AlterUniqueTogether(
            name='requestlist',
            unique_together=set([('user_email', 'requested_user_email'), ('requested_user_email', 'user_email')]),
        ),
    ]
